id: PA599442E
initial_creation_type: input
source_metadata:
  title: Śāntigarbha
  language: en
  description: 'Texts by and about Śāntigarbha (zhi ba''i snying po), renowned as
    one of the eight vidyādharas of India:'
  volume:
    0f412d30e1e6440189ac3aa780a80d1a:
      title: A Praise to the Lotus King
      parent: Praise
created_at: '2022-03-01T02:23:34.706138'
last_modified_at: '2022-03-01T02:23:34.706144'
